apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lumio
resources:
  - ../base
  - ingress.yaml
configMapGenerator:
  - name: lumio-config
    envs:
      - config.env
generators:
  - secret-generator.yaml
images:
  - name: lumio-web
    newName: ghcr.io/nightnoryu/lumio
    newTag: REPLACE_WITH_RELEASE
  - name: lumio-worker
    newName: ghcr.io/nightnoryu/lumio-worker
    newTag: REPLACE_WITH_RELEASE
