apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lumio

resources:
  - ../base
  - configmap.yaml
  - middlewares.yaml
  - s3-ingress.yaml
  - web-ingress.yaml

generators:
  - secret-generator.yaml

patches:
  - target:
      kind: Secret
      name: lumio-secrets
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          app.kubernetes.io/component: prerequisite

images:
  - name: lumio-web
    newName: ghcr.io/nightnoryu/lumio
    newTag: 0.1.1
  - name: lumio-worker
    newName: ghcr.io/nightnoryu/lumio-worker
    newTag: 0.1.1
