apiVersion: v1
kind: Secret
metadata:
    name: lumio-secrets
    namespace: lumio
type: Opaque
stringData:
    LUMIO_DB_PASSWORD: ENC[AES256_GCM,data:JS5YC1WBki4hNnmTujOZig==,iv:n0H21nD6pcsmadquV8H5GJJxrXXenjEk9ryA86mBN2I=,tag:ojGIjEsKhxkST9ufNwq+UA==,type:str]
    LUMIO_S3_ACCESS_KEY: ENC[AES256_GCM,data:SpUxup0WOaTd,iv:4j6gqmVZWLly2T3mRojKt/DF8wM5XgFOk71bljpu0zs=,tag:wxvLbfV+EVkUtSe6e/zYcg==,type:str]
    LUMIO_S3_SECRET_KEY: ENC[AES256_GCM,data:FM0EZJkmwnaF5VmGSdnL1A==,iv:SDWdxLtnoIKrKcS0+ACikkPEOXA1cz2XMNc18xUdjn4=,tag:SbZqvdb4OmIZpZbNg7E9kw==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:sLmkJ3FIkKiIKLo=,iv:FtZQ6opB92pcJkjq3stNGrZ0KnS00cg+d5QOEEzkXT0=,tag:e5EJ7pToph3EB3G1Bap1+Q==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:hJ9oSrlaV86QoQR+uavmCg==,iv:FTVynLck0ltCQX3bJE5X36pUsh6QSs2kNbdGbUeauo8=,tag:j1LyvWZpAwdYXN4+fM5XRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN2hXUXcyMUN4SGp5UDN2
            cDQ0emt6V2w4L0JWV2F3ZTQyRVNiNmhLNFFrCnppeG92Y2IrZnpLZjVxUHlPVlZj
            RExUR1o4NG9OV2cvNVR0endVaWhtM3cKLS0tIHFOdllCdnZ1dEFuTzJDOFoxeEll
            ejkzVnNLaThrcS9QSE5kbWJ1eVFXTkUKc9jDKqlee57VFu3dlzZodT+n9sgS7Xfx
            aeFiPxE/pfFxFDWWK9KZ9M58KFgv2wM7QWTm6PwI50kjuWnkXZfG5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T19:05:31Z"
    mac: ENC[AES256_GCM,data:qJWD2C6vCNVqfRPkP0E2qQXHKRBg3yTkOicaxz0YggXcdr8rby+9TKkxPyoUSTLZ3wZtZiNVsiV17e+ZL0LxYARoqA506AHLPEkvcv6qcCZ2rYbU+XYhXfxX5Vg+W7E9KgRa8d6o1oJuqtZCleeSdLGMfPkJpnQnCRkphGqIHKY=,iv:Fc+zBNwqbV20tHQ96qvSYSPl4meTaNDJTIc+78LXRtE=,tag:7Q0EZpCuvpUrd/oKqJeldg==,type:str]
    version: 3.13.3
