apiVersion: v1
kind: Secret
metadata:
    name: lumio-secrets
    namespace: lumio
type: Opaque
stringData:
    LUMIO_DB_PASSWORD: ENC[AES256_GCM,data:8/4VmYcvx/4ttH0b/W5z24Tp8z8UZf+VxzJjLqDLIk192uBYIA==,iv:hCfRtNZ018HLYBw65Iqvj9Zj0rQtOSSa3XZI3iO7LGI=,tag:tmtnCOUM05QsaeqsQLlEJQ==,type:str]
    LUMIO_S3_ACCESS_KEY: ENC[AES256_GCM,data:SpUxup0WOaTd,iv:4j6gqmVZWLly2T3mRojKt/DF8wM5XgFOk71bljpu0zs=,tag:wxvLbfV+EVkUtSe6e/zYcg==,type:str]
    LUMIO_S3_SECRET_KEY: ENC[AES256_GCM,data:lIP0wpgBJwKiSmzFa1kMV7oh4JHSMJ8pQgB4p1I4,iv:8eP+kbV8b4KYk0KOX+NEpdKrPwQyschu0WV+AFBrrMY=,tag:oPkHut6zCVSQ9OZHnNOZkg==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:sLmkJ3FIkKiIKLo=,iv:FtZQ6opB92pcJkjq3stNGrZ0KnS00cg+d5QOEEzkXT0=,tag:e5EJ7pToph3EB3G1Bap1+Q==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:vmRjRP3AmASKct5pvkbEjX/p+hp4Ag/p24h/S+Jd1lM=,iv:iSMwkG3CF3RfoRdb5yP+OWBEwnwJ4ByWU76WyBngAaE=,tag:YoRVwA4QRUAj7uayNF59jg==,type:str]
sops:
    age:
        - recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN2hXUXcyMUN4SGp5UDN2
            cDQ0emt6V2w4L0JWV2F3ZTQyRVNiNmhLNFFrCnppeG92Y2IrZnpLZjVxUHlPVlZj
            RExUR1o4NG9OV2cvNVR0endVaWhtM3cKLS0tIHFOdllCdnZ1dEFuTzJDOFoxeEll
            ejkzVnNLaThrcS9QSE5kbWJ1eVFXTkUKc9jDKqlee57VFu3dlzZodT+n9sgS7Xfx
            aeFiPxE/pfFxFDWWK9KZ9M58KFgv2wM7QWTm6PwI50kjuWnkXZfG5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T11:35:08Z"
    mac: ENC[AES256_GCM,data:b61kqlDC0pPca71YyNtNsSdFP0baShKiOuDYgK0ARqoQd7tQG9t8G4cpBcyGpXsdXeNDZUQmW+hgtCu/AeIuuH+Zuq9GFA9KHhRVju3RgKEE8jKXl/cU/UdiOE4vT9K0E9pGnuQGKSxepj182DiRM3GXVGby3553Gp/+ZBNCg3M=,iv:l88CB97jJwdArs4EVXF48Xj+VA22nGgS6QYTAvl77Tk=,tag:v22Vjei6EI9ertz4PHxhIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
