apiVersion: v1
kind: Secret
metadata:
    name: lumio-secrets
    namespace: lumio
type: Opaque
stringData:
    LUMIO_DB_PASSWORD: ENC[AES256_GCM,data:uCfZRxdXEoGrraUpw3Tra4wEYx9o2SmXBje8Q4rx,iv:vZG0LYE8JWjLbktBQfpEWdhN+UGB2s861sROghaz03Q=,tag:+gOjOUh4QyLge6up/w7JRA==,type:str]
    LUMIO_S3_ACCESS_KEY: ENC[AES256_GCM,data:P10s6FYgtIqKdueR8w0EdeQ+kq2HkKitMsM=,iv:cp08tCRXij8dj/L37zgaa1RqG5AvdmJy2EpdtoZjHxQ=,tag:xgr/2JuKfyT3MlXa8sRviw==,type:str]
    LUMIO_S3_SECRET_KEY: ENC[AES256_GCM,data:csBZr/e84DAbzB7BlcfBXXV6gLzPkB2QVUhsiirl,iv:25fSww2CjeLt4uINadBG/wHjYZsSNhtoli/Xi8jLwNQ=,tag:5j+EGkL6esF5RpJKxSsMzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWmVaZDk3Sk51QlVlWC9H
            MnF1OUM0S3hiOWN4SUpBVFZJektJTzRsbTA0CjFNaERUVzhyL3cwbmsyOTE1aHND
            cFcwSnVsR21Wc0d3eHAwbHEyL1ZnMEkKLS0tIFJQSzNhcXZKNmdQZTlkNTF2d01r
            NWNMdFlqUHRVa3Mwejc5VG8ycEZ5Y00KiSygqRDa5GSmStrbGy52O7Rv+ECHkq00
            ZL0+5xZ+WjN6gGgtwRQ0DHCQ8gneiv59hY5i81LlO3n1Ovv5gMTJVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s9fqc3qeh7qxkdnarj5jrcn4tjehjukp9p30n28phe8205mnvpzqc47z8m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T09:37:37Z"
    mac: ENC[AES256_GCM,data:XBcItQhuk8y27ZYVCuPbAvp82Ja5PDUeFd7cxV39MYggzupxRXXUt8HmGNuepAzKt8A8P8rXXyqlTOPoj4/Pdfx2eFoY6CoiIGHV9WkYLu0IknRDEBs2OXZ/5b6cHeeszWcEa3TljgExcsR+VuPY8dniaGASjOb38G35OFqH2Bo=,iv:9SEoHPU13iafGllP1i/XXAwt5nf71OdF5zC7PUTYqI4=,tag:FS6H0Nm1zLtttplRd1f67w==,type:str]
    version: 3.13.3
