apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
data:
  garage.toml: |
    metadata_dir = "/data/meta"
    data_dir = "/data/blocks"
    db_engine = "sqlite"
    replication_factor = 1
    rpc_bind_addr = "0.0.0.0:3901"
    rpc_secret_file = "/data/rpc-secret"

    [s3_api]
    api_bind_addr = "0.0.0.0:3900"
    s3_region = "garage"
