openapi: 3.0.0

info:
  title: Lumio public API
  version: 0.1.0

security:
  - sessionAuth: [ ]

paths:
  /api/register:
    post:
      operationId: Register
      summary: Registers a new user
      tags: [ Users ]
      security: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestBody'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponseBody'
        '400':
          $ref: '#/components/responses/BadRequest'

  /api/login:
    post:
      operationId: Login
      summary: Logs in the user and returns token
      tags: [ Users ]
      security: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestBody'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseBody'
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  securitySchemes:
    sessionAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Session ID passed via the Authorization header

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestResponseBody'

  schemas:
    BadRequestResponseBody:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        message:
          type: string
          example: Invalid data
        data:
          $ref: '#/components/schemas/ErrorData'
      required:
        - code
        - message

    ErrorCode:
      type: string
      enum:
        - invalid_input
        - not_found
        - permission_denied
        - operation_rejected
        - already_exists

    ErrorData:
      type: object
      additionalProperties: true
      description: additional information about the error

    RegisterRequestBody:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
          minLength: 8
      required:
        - username
        - password

    RegisterResponseBody:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
        - id

    LoginRequestBody:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
      required:
        - username
        - password

    LoginResponseBody:
      type: object
      properties:
        token:
          type: string
      required:
        - token
